batch_size: 8
criterion: loss.Hybrid3ChanLoss
criterion_args:
  ce_coef: 0.0
  focal_coef: 0.6
  weights: [1.0, 1.2, 1.2]
data_dir: /mnt/hdd/datasets/spacenet/train/
dataset: dataset.SpacenetOffNadirDataset
dataset_args:
  image_types: [Pan-Sharpen, PAN, MS]
  make_border: true
  size: [900, 900]
epochs: 40
lr: 0.0001
lr_scheduler: StepLR
lr_scheduler_args: {gamma: 0.95, step_size: 1}
max_gpu_batch_size: 4
model: unet_resnet101
model_args: {pretrained: false}
model_dir: output/dlp_unethybrid_3
num_workers: 2
optimizer: Adam
optimizer_args: {}
save_model_frequency: 1
test_batch_size: 1
transformer: transforms.SpaceNetTransform
